Repository goorm-engineers4/Project3_MSA_people_of_delivery, pull requests merged in 2025-09, with the labels that each got.

#8 🔨 [REFACTOR] cart-service 내부 통신 cache redis cache로 변경
  auth-service/src/main/resources/application.yml
  cart-service/build.gradle
  cart-service/src/main/java/com/example/cloudfour/cartservice/client/UserClient.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/config/CacheConfig.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/config/RedisConfig.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/service/command/CartCommandService.java
  cart-service/src/main/resources/application.yml
  docker-compose.yml
  store-service/src/main/resources/application.yml
Labels: 🐞 BugFix, 🔨 Refactor

#15 ✨ [FEAT] Redis Lua Script 적용, Kafka 적용
  store-service/build.gradle
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/common/MenuCartResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/common/MenuOptionCartResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/common/StoreCartResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/common/UserAddressResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/common/enums/OrderStatus.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/common/enums/PaymentStatus.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/controller/InternalMenuController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/controller/InternalStockController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/converter/MenuConverter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/converter/MenuOptionConverter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/converter/StockConverter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/dto/OrderEvent.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/dto/PaymentEvent.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/dto/StockResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/enums/ReservationStatus.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/RedisInventoryService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/StockKafkaService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/StockRedisService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/command/StockCommandService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/query/MenuQueryService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/query/StockQueryService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/controller/InternalStoreController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/converter/StoreConverter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/service/query/StoreQueryService.java
  store-service/src/main/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor

#17 :sparkles: [FEAT] logback 적용
  ai-service/src/main/resources/logback-spring.xml
  auth-service/src/main/resources/logback-spring.xml
  cart-service/src/main/resources/logback-spring.xml
  payment-service/src/main/resources/logback-spring.xml
  store-service/src/main/resources/logback-spring.xml
  user-service/src/main/resources/logback-spring.xml
Labels: ✨ Feature

#19 🔨 [REFACTOR] FeignClient 적용
  auth-service/build.gradle
  auth-service/src/main/java/com/example/cloudfour/authservice/AuthServiceApplication.java
  auth-service/src/main/java/com/example/cloudfour/authservice/client/UserClient.java
  auth-service/src/main/java/com/example/cloudfour/authservice/client/UserFeignClient.java
  auth-service/src/main/java/com/example/cloudfour/authservice/config/RestTemplateConfig.java
  cart-service/build.gradle
  cart-service/src/main/java/com/example/cloudfour/cartservice/CartServiceApplication.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/client/StoreClient.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/client/StoreFeignClient.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/client/UserClient.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/client/UserFeignClient.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/config/FeignConfig.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/config/RestTemplateConfig.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/config/SwaggerConfig.java
  cart-service/src/main/resources/application.yml
  module-common/build.gradle
  module-common/src/main/java/com/example/cloudfour/modulecommon/error/RestTemplateResponseErrorHandler.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/passport/interceptor/FeignPassportInterceptor.java
  payment-service/build.gradle
  payment-service/src/main/java/com/example/cloudfour/paymentservice/PaymentServiceApplication.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/config/FeignConfig.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/config/RestTemplateConfig.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/config/SwaggerConfig.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/config/TossFeignConfig.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/OrderClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/OrderFeignClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/StoreClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/StoreFeignClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/TossApiClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/TossFeginClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/UserClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/UserFeginClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/dto/OrderStatusUpdateRequestDTO.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/dto/PaymentRequestDTO.java
  store-service/build.gradle
  store-service/src/main/java/com/example/cloudfour/storeservice/StoreServiceApplication.java
  store-service/src/main/java/com/example/cloudfour/storeservice/client/UserClient.java
  store-service/src/main/java/com/example/cloudfour/storeservice/config/FeignConfig.java
  store-service/src/main/java/com/example/cloudfour/storeservice/config/RestTemplateConfig.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/service/query/ReviewQueryService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/service/query/StoreQueryService.java
Labels: ✨ Feature, 📃 Docs, 🔨 Refactor

#28 ✨ [FEAT] Circuit Breaker 적용
  auth-service/build.gradle
  auth-service/src/main/java/com/example/cloudfour/authservice/client/UserFeignClient.java
  auth-service/src/main/java/com/example/cloudfour/authservice/domain/auth/service/EmailServiceImpl.java
  auth-service/src/main/resources/application-prod.yml
  auth-service/src/main/resources/application.yml
  cart-service/build.gradle
  cart-service/src/main/java/com/example/cloudfour/cartservice/client/StoreFeignClient.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/client/UserFeignClient.java
  cart-service/src/main/resources/application-prod.yml
  cart-service/src/main/resources/application.yml
  module-common/build.gradle
  module-common/src/main/java/com/example/cloudfour/modulecommon/curcuitBreaker/CircuitBreakerRegistryEventConsumer.java
  payment-service/build.gradle
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/OrderFeignClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/StoreFeignClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/TossFeginClient.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/apiclient/UserFeginClient.java
  payment-service/src/main/resources/application-prod.yml
  payment-service/src/main/resources/application.yml
  store-service/build.gradle
  store-service/src/main/java/com/example/cloudfour/storeservice/client/UserClient.java
  store-service/src/main/resources/application-prod.yml
  store-service/src/main/resources/application.yml
Labels: ✨ Feature

#52 :memo: [DOCS] codeRabbit 적용
  .coderabbit.yaml
Labels: 📃 Docs

#49 🧪 [TEST] auth-service 테스트 코드 생성
  auth-service/src/test/java/com/example/cloudfour/authservice/client/UserClientTest.java
  auth-service/src/test/java/com/example/cloudfour/authservice/domain/auth/controller/AuthControllerIT.java
  auth-service/src/test/java/com/example/cloudfour/authservice/domain/auth/service/AuthServiceTest.java
  auth-service/src/test/java/com/example/cloudfour/authservice/domain/auth/service/JwtServiceTest.java
  auth-service/src/test/java/com/example/cloudfour/authservice/domain/passport/controller/PassportControllerIT.java
  auth-service/src/test/java/com/example/cloudfour/authservice/domain/passport/service/PassportServiceTest.java
  auth-service/src/test/java/com/example/cloudfour/authservice/util/RedisUtilTest.java
  auth-service/src/test/java/com/example/cloudfour/authservice/util/VerificationCodeHasherTest.java
Labels: :test_tube: Test

#54 :test_tube: [TEST] store-service test 코드 작성
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/menu/service/RedisInventoryServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/menu/service/command/StockCommandServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/menu/service/query/MenuQueryServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/menu/service/query/StockQueryServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/review/service/command/ReviewCommandServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/review/service/query/ReviewQueryServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/store/service/command/StoreCommandServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/store/service/query/StoreQueryServiceTest.java
Labels: :test_tube: Test

#58 🔨 [REFACTOR] kafka 설정 수정 및 dlq 알림 추가
  auth-service/src/main/resources/application.yml
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/service/command/OrderCommandHandler.java
  cart-service/src/main/resources/application.yml
  module-common/src/main/java/com/example/cloudfour/modulecommon/config/DlqTopicResolver.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/config/KafkaConfig.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/converter/OrderCommandConverter.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/idempotency/MessageIdempotencyService.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/idempotency/ProcessedMessage.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/idempotency/ProcessedMessageRepository.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/messaging/DLQListener.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/messaging/DLQMonitor.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/messaging/MessagePublisher.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/messaging/SagaAwareDLQHandler.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/monitoring/DiscordNotifier.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/monitoring/NotificationService.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/outbox/scheduler/OutboxRetryScheduler.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/saga/listener/SagaEventListener.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/saga/service/SagaOrchestrator.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/schedule/OrderTimeoutHandler.java
  module-common/src/main/java/com/example/cloudfour/modulecommon/schedule/ScheduledTaskService.java
  module-common/src/main/resources/application.yml
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/service/PaymentCommandHandler.java
  payment-service/src/main/resources/application.yml
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/InventoryCommandHandler.java
  store-service/src/main/resources/application.yml
  user-service/src/main/java/com/example/cloudfour/userservice/config/SecurityConfig.java
  user-service/src/main/resources/application.yml
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor
